---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: https://api.stackbit.com/project/5db2e6ac95652000145cbfe9/webhook/forestry
sections:
- type: document
  path: _config.yml
  label: Global site config
  templates:
  - config
- type: document
  path: index.md
  label: Главная forestry
  templates:
  - index
- type: directory
  path: ''
  label: Страница forestry
  create: all
  match: "**/*.md"
  exclude: "{README.md,LICENSE.md,index.md,store.md,faq.md,about.md}"
  templates:
  - page
- type: document
  path: store.md
  label: Меню forestry
  templates:
  - store
- type: document
  path: faq.md
  label: тут вопросы и ответы foretry
  templates:
  - faq
- type: document
  path: about.md
  label: О компании forestry
  templates:
  - about
- type: directory
  path: category
  label: Категории forestry
  create: all
  match: "**/*"
  templates:
  - categories
- type: document
  path: _data/promotion.json
  label: Советы forestry
  templates:
  - promotion
- type: document
  path: _data/testimonials.json
  label: Отызы forestry
  templates:
  - testimonials
- type: directory
  path: products
  label: Товары foresty
  create: all
  match: "**/*"
  templates:
  - products
- type: document
  path: _data/menus.yml
  label: Веб-сайт Меню forestry
  templates:
  - site_menus
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
